# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-08 05:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_text2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text2',
        ),
        migrations.AddField(
            model_name='post',
            name='ticket',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
