# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-08 05:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190108_0746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='ticket',
            new_name='active',
        ),
    ]
