# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-08 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190108_0754'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deps', models.CharField(choices=[('HR', 'Human Resources'), ('TECH', 'Technical'), ('FINANCE', 'Finance')], default='HR', max_length=2)),
            ],
        ),
    ]
