# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-08 06:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Department',
        ),
    ]
