# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-08 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190108_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='active',
            field=models.BooleanField(),
        ),
    ]
