# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-08 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190108_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dep',
            field=models.CharField(max_length=200),
        ),
    ]
